# Generated by Django 4.2.23 on 2025-08-06 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingpoll',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='votingpoll',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='voting_polls/', verbose_name='file'),
        ),
        migrations.AddField(
            model_name='votingpoll',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='is public'),
        ),
        migrations.AddField(
            model_name='votingpoll',
            name='is_result_published',
            field=models.BooleanField(default=False, verbose_name='is result published'),
        ),
        migrations.AddField(
            model_name='votingpoll',
            name='is_voting',
            field=models.BooleanField(default=False, verbose_name='is voting'),
        ),
        migrations.AddField(
            model_name='votingpoll',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='link'),
        ),
        migrations.AddField(
            model_name='votingpoll',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start date'),
        ),
    ]
