# Generated by Django 4.2.23 on 2025-08-06 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_votingpoll_end_date_votingpoll_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votingpoll',
            name='file',
        ),
        migrations.AddField(
            model_name='votingpoll',
            name='file_link',
            field=models.URLField(blank=True, null=True, verbose_name='file link'),
        ),
    ]
