# Generated by Django 4.2.23 on 2025-07-12 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteBooth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_at', models.DateField(verbose_name='vote start date')),
                ('end_at', models.DateField(verbose_name='vote end date')),
                ('is_active', models.BooleanField(default=True, verbose_name='active status')),
                ('candidates', models.ManyToManyField(related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='candidate')),
                ('union', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='locations.union', verbose_name='union')),
                ('voters', models.ManyToManyField(related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='voters')),
            ],
            options={
                'verbose_name': 'vote_booth',
                'verbose_name_plural': 'vote_booths',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('vote_booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_govt.votebooth')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vote',
                'verbose_name_plural': 'votes',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200, verbose_name='position')),
                ('areas', models.CharField(max_length=200, verbose_name='working areas')),
                ('start_at', models.DateField(verbose_name='working start date')),
                ('end_at', models.DateField(verbose_name='working end date')),
                ('is_active', models.BooleanField(default=True, verbose_name='active status')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified status')),
                ('union', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='locations.union', verbose_name='union')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'member',
                'verbose_name_plural': 'members',
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=100)),
                ('areas', models.CharField(blank=True, max_length=200, null=True, verbose_name='working areas')),
                ('start_at', models.DateField(verbose_name='working start date')),
                ('end_at', models.DateField(verbose_name='working end date')),
                ('is_active', models.BooleanField(default=True, verbose_name='active status')),
                ('Contributor', models.ManyToManyField(related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('union', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='locations.union', verbose_name='union')),
            ],
            options={
                'verbose_name': 'contribution',
                'verbose_name_plural': 'contributions',
            },
        ),
    ]
