# Generated by Django 4.2.7 on 2025-03-21 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("local_govt", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_title", models.CharField(max_length=100)),
                (
                    "areas",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="working areas",
                    ),
                ),
                ("start_at", models.DateField(verbose_name="working start date")),
                ("end_at", models.DateField(verbose_name="working end date")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="active status"),
                ),
                (
                    "Contributor",
                    models.ManyToManyField(
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
                (
                    "localgovt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="local_govt.localgovt",
                        verbose_name="local govt",
                    ),
                ),
            ],
            options={
                "verbose_name": "contribution",
                "verbose_name_plural": "contributions",
            },
        ),
    ]
