# Generated by Django 4.2.23 on 2025-07-13 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('local_govt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='local_govt.member', verbose_name='member'),
        ),
    ]
