# Generated by Django 4.2.7 on 2025-03-22 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("local_govt", "0002_contribution"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoteBooth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vote_title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("start_at", models.DateField(verbose_name="vote start date")),
                ("end_at", models.DateField(verbose_name="vote end date")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="active status"),
                ),
                (
                    "candidates",
                    models.ManyToManyField(
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="candidate",
                    ),
                ),
                (
                    "localgovt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="local_govt.localgovt",
                        verbose_name="local govt",
                    ),
                ),
                (
                    "voters",
                    models.ManyToManyField(
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="voters",
                    ),
                ),
            ],
            options={
                "verbose_name": "vote_booth",
                "verbose_name_plural": "vote_booths",
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vote", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "vote_booth",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="local_govt.votebooth",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "vote",
                "verbose_name_plural": "votes",
            },
        ),
    ]
