# Generated by Django 4.2.7 on 2025-07-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_govt', '0003_votebooth_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='verified status'),
        ),
        migrations.AddField(
            model_name='member',
            name='union_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='union id'),
        ),
        migrations.AddField(
            model_name='member',
            name='union_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='union'),
        ),
    ]
