# Generated by Django 4.2.7 on 2025-03-21 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("local_govt", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("file", models.FileField(blank=True, null=True, upload_to="uploads/")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "localgovt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="local_govt.localgovt",
                        verbose_name="local goverment",
                    ),
                ),
            ],
            options={
                "verbose_name": "notice",
                "verbose_name_plural": "notices",
                "db_table": "notice",
            },
        ),
    ]
