# Generated by Django 4.2.7 on 2025-03-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="end",
            new_name="duration",
        ),
        migrations.AddField(
            model_name="event",
            name="description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
