# Generated by Django 4.2.7 on 2025-08-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='members',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
