# Generated by Django 4.2.7 on 2025-03-21 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("local_govt", "0001_initial"),
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Even",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("start", models.DateTimeField()),
                ("link", models.URLField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "localgovt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="local_govt.localgovt",
                        verbose_name="local goverment",
                    ),
                ),
            ],
            options={
                "verbose_name": "even",
                "verbose_name_plural": "evens",
                "db_table": "even",
            },
        ),
    ]
