# Generated by Django 4.2.7 on 2025-03-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0002_rename_end_event_duration_event_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="duration",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
