# Generated by Django 4.2.23 on 2025-07-12 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('file', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('acepted', 'Acepted'), ('canceled', 'Canceled'), ('on_progress', 'On Progress'), ('done', 'Done')], default='pending', max_length=11, verbose_name='status')),
                ('possibility_amount', models.FloatField(default=0)),
                ('possibility_time_required', models.DateField(blank=True, null=True)),
                ('requested_citizen', models.ForeignKey(help_text='Who sent the request to solve the issue', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='request')),
                ('taken_member', models.ForeignKey(blank=True, help_text='Who is taking the responsibility to solve the issue', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='taken member')),
                ('union', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='locations.union', verbose_name='union')),
            ],
            options={
                'verbose_name': 'request',
                'verbose_name_plural': 'requests',
            },
        ),
    ]
