# Generated by Django 4.2.23 on 2025-07-13 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('local_govt', '0001_initial'),
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='taken_member',
            field=models.ForeignKey(blank=True, help_text='Who is taking the responsibility to solve the issue', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='local_govt.member', verbose_name='taken member'),
        ),
    ]
