# Generated by Django 4.2.23 on 2025-07-12 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='localgovt',
        ),
        migrations.AddField(
            model_name='request',
            name='union',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='locations.union', verbose_name='union'),
        ),
        migrations.AlterField(
            model_name='request',
            name='requested_citizen',
            field=models.ForeignKey(help_text='Who sent the request to solve the issue', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='request'),
        ),
        migrations.AlterField(
            model_name='request',
            name='taken_member',
            field=models.ForeignKey(blank=True, help_text='Who is taking the responsibility to solve the issue', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='taken member'),
        ),
    ]
